// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendLog(arg1) {
  return window['go']['main']['App']['BackendLog'](arg1);
}

export function Config() {
  return window['go']['main']['App']['Config']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ManualUpdate() {
  return window['go']['main']['App']['ManualUpdate']();
}

export function ShouldUpdate() {
  return window['go']['main']['App']['ShouldUpdate']();
}

export function StartExecutable() {
  return window['go']['main']['App']['StartExecutable']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}

export function UpdateCurrentFileData(arg1, arg2) {
  return window['go']['main']['App']['UpdateCurrentFileData'](arg1, arg2);
}

export function UpdateDownloadProgress(arg1) {
  return window['go']['main']['App']['UpdateDownloadProgress'](arg1);
}

export function UpdateDownloadStatus(arg1) {
  return window['go']['main']['App']['UpdateDownloadStatus'](arg1);
}
