// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackendLog(arg1:string):Promise<void>;

export function Config():Promise<main.Config>;

export function ManualUpdate():Promise<void>;

export function ShouldUpdate():Promise<boolean>;

export function StartExecutable():Promise<void>;

export function Update():Promise<void>;

export function UpdateCurrentFileData(arg1:string,arg2:number):Promise<void>;

export function UpdateDownloadProgress(arg1:number):Promise<void>;

export function UpdateDownloadStatus(arg1:string):Promise<void>;
